### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [pawel850m/tictactoe_three_pawns#1]
1. Wszystkie 3 katalogi do wyrzucenia. *Vide* 1. rozdział Poradnika.
2. Pylint pomoże Panu opanować białe znaki (2. rozdział).
3. Stałe 15, 10, 7, 2, 0.1, 7.2 itp. nazwać (2. rozdział).
4. Zmienne globalne w `main.py` wepchać do klasy (2. rozdział).
5. Funkcje `button_number_changer()`, `win_signal()` i `reset()` nie mogą wyglądać jak dzieło przedszkolaka. Proszę te przyciski trzymać w 9-elementowej liście.
6. [To](https://github.com/pawel850m/tictactoe_three_pawns/blob/96300d631c34f98492d3dfad88e5ba0a780be8de/boardclass.py#L3) nie działa tak, jak Pan przypuszcza (`board` staje się atrybutem wspólnym dla wszystkich obiektów tej klasy, co nie ma znaczenia, bo i tak zostanie przesłonięte przez `self.board`). Wyrzucić.

**Comment by MarcinCiura** [comment]
1. [Czemu dwa rodzaje cudzysłowów](https://github.com/pawel850m/tictactoe_three_pawns/blob/00f26852a731b17747c603b1cdcb1162ca7655e6/boardclass.py#L22)?
2. [Tak być nie może](https://github.com/pawel850m/tictactoe_three_pawns/blob/00f26852a731b17747c603b1cdcb1162ca7655e6/boardclass.py#L11) (3, rozdział). Stałe zostawić, tylko nazwać dużymi literami, resztę — jeśli potrzebna — inicjalizować w konstruktorze. Wszystkie funkcje z pliku `main.py`, które operują na planszy, powinny być metodami tej klasy.
3. [To nic nie robi](https://github.com/pawel850m/tictactoe_three_pawns/blob/00f26852a731b17747c603b1cdcb1162ca7655e6/main.py#L427).
4. [To powkładać do `main()`](https://github.com/pawel850m/tictactoe_three_pawns/blob/00f26852a731b17747c603b1cdcb1162ca7655e6/main.py#L17) (3, rozdział). Nadto słuchać pylinta w sprawie stylu nazw.
5. [Zamiast tego](https://github.com/pawel850m/tictactoe_three_pawns/blob/00f26852a731b17747c603b1cdcb1162ca7655e6/main.py#L278) przygotować stałą listę trójek pól do sprawdzania:
```pylint
CHECKED_FIELDS = [
    (0, 1, 2),
    (3, 4, 5),
    itd.,
]
```
i użyć pętli.
6. [Połowa drogi za Panem](https://github.com/pawel850m/tictactoe_three_pawns/blob/00f26852a731b17747c603b1cdcb1162ca7655e6/main.py#L354), ale proszę użyć pętli do tworzenia tych przycisków.

**Comment by MarcinCiura** [comment]
Proszę dawać znać, że coś jest gotowe, tutaj, a nie emailem.
1. [`computer_shape` i `player_shape`](https://github.com/pawel850m/tictactoe_three_pawns/blob/18d62ad3068a4b96090073f1ff79d3e7e137d615/boardclass.py#L13) to stałe, nie zmienne. Nie inicjalizować ich w konstruktorze, tylko albo na górze pliku, albo w klasie, i nazwać dużymi literami (2. rozdział).
2. Dlaczego Pan wyjął `initial_set` z konstruktora `Board`? Przecież nie przewiduje Pan innych plansz niż 3x3. Teraz powtarza Pan *N* razy swoje 9 spacji (nota bene można z nich zrobić `[' '] * 9`).
3. W testach powyrzucać zbędne docstringi w klasie i metodach. Za to można metody testujące nazywać dłuższymi nazwami. Dorobić jeszcze ze 2 testy innych przypadków do `win_checker()`: wygrana kółek, brak wygranej.

**Comment by PawelNizialek** [comment]
Szanowny Panie Doktorze,
zastosowałem się do powyższych uwag. Gra oferuje możliwość zmiany kształtu, dlatego nie inicjalizowałem tych zmiennych jako stałe.
Z poważaniem
Paweł Niziałek

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość.
1. Z 3 i 9 zrobić nazwane stałe i ich używać.. 
2. [Tu](https://github.com/pawel850m/tictactoe_three_pawns/blob/1c073408b29a19bad0454d1c161ec085bc5e50c6/boardclass.py#L37) można użyć `self.board[i] == self.board[i + 3] == self.board[i + 6]`. To samo gdzie indziej.
3. Wartości zwracane przez `win_checker()` nazwać i ich używać.
4. [Tu](https://github.com/pawel850m/tictactoe_three_pawns/blob/1c073408b29a19bad0454d1c161ec085bc5e50c6/boardclass.py#L40) pisać po prostu
```python
if ...:
    return COMPUTER_LOST
return COMPUTER_WON
```
itd.
5. Co [to](https://github.com/pawel850m/tictactoe_three_pawns/blob/1c073408b29a19bad0454d1c161ec085bc5e50c6/boardclass.py#L61) znaczy? Nie jest opisane w docstringu. Nie podoba mi się zwracanie liczb, a tu nagle `None`.
6. Testy fajne, ale stałe `NUMBER_OF_...` wyrzucić i do [tego](https://github.com/pawel850m/tictactoe_three_pawns/blob/1c073408b29a19bad0454d1c161ec085bc5e50c6/boardclass_test.py#L33) i podobnych miejsc doczytać w 3. rozdziale o pytonicznych i niepytonicznych pętlach.
7. To samo [tutaj](https://github.com/pawel850m/tictactoe_three_pawns/blob/1c073408b29a19bad0454d1c161ec085bc5e50c6/main.py#L272) i w podobnych miejscach, Nadto pisać
```python
if ... != shape:
    break
```
ad 1. Teraz widzę. Niestety [ta funkcja](https://github.com/pawel850m/tictactoe_three_pawns/blob/1c073408b29a19bad0454d1c161ec085bc5e50c6/main.py#L300) jest antyobiektowa: zmienia stan obiektu na żywca (4. rozdział). Poprawne rozwiązanie to zastąpienie zmiennych globalnych atrybutami klasy, przerobienie większości treści `main.py` na klasę, a w jej metodzie `set_game()` wywoływanie konstruktora klasy `Board` z nowymi parametrami, które będą odpowiadać za poziom trudności i to, kto czym gra.

Dodatkowa prośba: jeśli nikt tego przed Panem nie zrobi, proszę ogłosić konsultacje w niedzielę o 20:30 i w poniedziałek o 12:00 pod standardowym linkiem. Dziękuję!

**Comment by PawelNizialek** [comment]
Dobry wieczór,
zastosowałem się do powyższych uwag

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Oto kolejne uwagi.
1. Magiczne `'O`' i `'X'` nazwać i używać tych nazw.
2. [Tu](https://github.com/pawel850m/tictactoe_three_pawns/blob/4622bd7cb3584e7b0514509ec4c0b808b37e5429/boardclass.py#L59) użyć `range(0, 9, 3)` z Pańskimi nazwanymi stałymi.
3. [To](https://github.com/pawel850m/tictactoe_three_pawns/blob/4622bd7cb3584e7b0514509ec4c0b808b37e5429/boardclass.py#L53) i podobne miejsca sformatować tak:
```python
if (... and
    ... == ... == ... and
    ... == ... == ...):
```
4. W przypadku `range(0, ...)` pierwsze zero jest zbędne. Powyrzucać.
5. [Te pętle](https://github.com/pawel850m/tictactoe_three_pawns/blob/4622bd7cb3584e7b0514509ec4c0b808b37e5429/boardclass_test.py#L31) zamienił Pan z niefajnych na bardzo niefajne. Ma być tak:
```python
for field_list in CHECKED_FIELDS:
    board = [' '] * 9
    for field in field_list:
        board[field] = CROSS
    ...
```
6. [Tu](https://github.com/pawel850m/tictactoe_three_pawns/blob/4622bd7cb3584e7b0514509ec4c0b808b37e5429/main.py#L72) pisać po prostu `move = int(number) - 1`.
7. [To](https://github.com/pawel850m/tictactoe_three_pawns/blob/4622bd7cb3584e7b0514509ec4c0b808b37e5429/main.py#L74) jest złe. Ma być `if 0 <= move < ...:`.
8. Funkcja `player()` zawsze zwraca zero. A tego zwróconego zera nawet Pan nie używa. Pisać po prostu `return` tam, gdzie trzeba (na końcu funkcji nie trzeba).
9. [Tu](https://github.com/pawel850m/tictactoe_three_pawns/blob/4622bd7cb3584e7b0514509ec4c0b808b37e5429/main.py#L181) też użyć pytonicznej pętli (3. rozdział). To samo niżej w wielu miejscach.
10. [Tu](https://github.com/pawel850m/tictactoe_three_pawns/blob/4622bd7cb3584e7b0514509ec4c0b808b37e5429/main.py#L211) użyć enumerate.

**Comment by PawelNizialek** [comment]
Dzień dobry,
wprowadziłem kolejne zmiany

**Comment by MarcinCiura** [comment]
1. [To](https://github.com/pawel850m/tictactoe_three_pawns/blob/a31debe267641c08bba2542093728f1a65c73ffa/boardclass.py#L52) jest pokręcone. Pisać
```python
if ...:
    return COMPUTER_LOST
else:
    return COMPUTER_WON
```
(podobnie już jest niżej).
2. [`for i, field in enumerate(GameBoardCopy.board):`](https://github.com/pawel850m/tictactoe_three_pawns/blob/a31debe267641c08bba2542093728f1a65c73ffa/main.py#L219) (3. rozdział). To samo gdzie indziej.

Po wprowadzeniu tych poprawek będę mógł zaliczyć Pana projekt.

**Comment by PawelNizialek** [comment]
Zastosowałem się do powyższych uwag.

**Comment by MarcinCiura** [comment]
Dziękuję. Tymczasem przyszły mi do głowy jeszcze dwie:
1. Z `' '` też zrobić nazwaną stałą.
2. A [tu](https://github.com/pawel850m/tictactoe_three_pawns/blob/23f30be23b32aad2284c77d82c9c2251f6842eff/boardclass.py#L68) co się zwróci, jeśli `count != NUMBER_OF_BUTTONS`? (Zwróci się `None`; niedobrze; poprawić).

**Comment by PawelNizialek** [comment]
Dokonałem zmian.

**Comment by MarcinCiura** [comment]
Przepraszam za przeoczenie Pana projektu. LGTM.

**Comment by PawelNizialek** [comment]
Szanowny Panie Doktorze,
dziękuję za poświęcony czas na ocenę mojego projektu oraz za cenne wskazówki.
Z wyrazami szacunku
Paweł Niziałek
